name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        # Disable C0103: invalid name
        # W0311: Bad indentation. (Decided to use 2 spaces instead of 4)
        # E0401: Import errors
        # R0912: Too many branches
        # R0913: Too many arguments
        # R0914: Too many local variables
        # R0915: Too many statements
        pylint --disable C0103,W0311,E0401,R0912,R0913,R0914,R0915 $(git ls-files '*.py' | grep -v "docs/" | grep -v setup.py)
