name: Test
on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@main
      with:
        environment-file: ./baredSC_dev_env.yml
        cache-downloads: true
        environment-name: baredSC_dev
    - name: pip install
      run: |
        micromamba activate baredSC_dev
        pip install .
    - name: Test baredSC
      run: |
        micromamba activate baredSC_dev
        pytest -v
